import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarLayout } from "@/components/app-sidebar/sidebar-layout";
import { createSupabaseClient } from "@/lib/supabase/server";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function getUser() {
  const supabase = await createSupabaseClient()
  const { data: { user } } = await supabase.auth.getUser()
  return user
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;

}>) {
  const user = await getUser()

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarLayout user={user}>
          {children}
        </SidebarLayout>
      </body>
    </html>
  );
}
